version: '3'

services:
  php:
    container_name: php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    env_file:
      - .env
    volumes:
      - ./app:/app
  mysql:
    container_name: mysql
    image: mysql:8.1
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    env_file:
      - .env

volumes:
  mysql_data: